<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class News extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('news')->insert([
            [
                'category_id' => 1,
                'image' => 'uploads/1.jpg',
                'title' => 'Tin nóng thế giới mới nhất',
                'slug' => Str::slug('Tin nóng thế giới mới nhất'),
                'content' => 'Cập nhật thông tin mới nhất về các sự kiện nóng đang diễn ra trên toàn thế giới.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'image' => 'uploads/2.jpg',
                'title' => 'Xu hướng công nghệ năm 2024',
                'slug' => Str::slug('Xu hướng công nghệ năm 2024'),
                'content' => 'Khám phá các xu hướng công nghệ dẫn đầu thị trường trong năm 2024 và những phát triển tiềm năng.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'image' => 'uploads/3.jpg',
                'title' => 'Thể thao: Kết quả trận đấu hôm qua',
                'slug' => Str::slug('Thể thao: Kết quả trận đấu hôm qua'),
                'content' => 'Tường thuật lại kết quả của các trận đấu bóng đá và các môn thể thao khác diễn ra hôm qua.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'image' => 'uploads/4.jpg',
                'title' => 'Tình hình kinh tế toàn cầu hiện nay',
                'slug' => Str::slug('Tình hình kinh tế toàn cầu hiện nay'),
                'content' => 'Phân tích chi tiết tình hình kinh tế toàn cầu và các yếu tố tác động đến thị trường quốc tế.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'image' => 'uploads/5.jpg',
                'title' => 'Sự phát triển của trí tuệ nhân tạo',
                'slug' => Str::slug('Sự phát triển của trí tuệ nhân tạo'),
                'content' => 'Trí tuệ nhân tạo đang thay đổi cách chúng ta sống, làm việc và ảnh hưởng đến các ngành công nghiệp.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 250,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'image' => 'uploads/6.jpg',
                'title' => 'Sức khỏe cộng đồng sau đại dịch',
                'slug' => Str::slug('Sức khỏe cộng đồng sau đại dịch'),
                'content' => 'Tình hình sức khỏe cộng đồng đang thay đổi và những thách thức mới sau đại dịch COVID-19.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'image' => 'uploads/7.jpg',
                'title' => 'Kinh tế Việt Nam phục hồi mạnh mẽ',
                'slug' => Str::slug('Kinh tế Việt Nam phục hồi mạnh mẽ'),
                'content' => 'Kinh tế Việt Nam đang dần phục hồi với nhiều tín hiệu lạc quan sau thời kỳ khó khăn vì đại dịch.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'image' => 'uploads/8.jpg',
                'title' => 'Giải pháp năng lượng tái tạo cho tương lai',
                'slug' => Str::slug('Giải pháp năng lượng tái tạo cho tương lai'),
                'content' => 'Năng lượng tái tạo đang trở thành giải pháp hàng đầu giúp phát triển bền vững và giảm thiểu khí thải.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'image' => 'uploads/9.jpg',
                'title' => 'Đổi mới giáo dục trong thời đại số',
                'slug' => Str::slug('Đổi mới giáo dục trong thời đại số'),
                'content' => 'Giáo dục đang trải qua cuộc cách mạng với sự phát triển công nghệ và thời đại số hóa.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 220,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'image' => 'uploads/10.jpg',
                'title' => 'Biến đổi khí hậu và hệ quả toàn cầu',
                'slug' => Str::slug('Biến đổi khí hậu và hệ quả toàn cầu'),
                'content' => 'Biến đổi khí hậu đang gây ra những hệ quả nặng nề cho toàn thế giới, cần các biện pháp khẩn cấp.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'image' => 'uploads/11.jpg',
                'title' => 'Thị trường bất động sản sôi động trở lại',
                'slug' => Str::slug('Thị trường bất động sản sôi động trở lại'),
                'content' => 'Sau thời gian trầm lắng, thị trường bất động sản bắt đầu sôi động trở lại với nhiều giao dịch lớn.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 350,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'image' => 'uploads/12.jpg',
                'title' => 'Thời trang bền vững: Xu hướng không thể bỏ qua',
                'slug' => Str::slug('Thời trang bền vững: Xu hướng không thể bỏ qua'),
                'content' => 'Thời trang bền vững đang trở thành xu hướng mới khi người tiêu dùng ngày càng quan tâm đến môi trường.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 290,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'image' => 'uploads/13.jpg',
                'title' => 'Phát triển công nghệ xanh cho tương lai',
                'slug' => Str::slug('Phát triển công nghệ xanh cho tương lai'),
                'content' => 'Công nghệ xanh đang là yếu tố then chốt để xây dựng tương lai bền vững và giảm thiểu tác động môi trường.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 310,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'image' => 'uploads/14.jpg',
                'title' => 'Nông nghiệp thông minh: Giải pháp mới cho tương lai',
                'slug' => Str::slug('Nông nghiệp thông minh: Giải pháp mới cho tương lai'),
                'content' => 'Nông nghiệp thông minh đang thay đổi cách quản lý trang trại, tăng năng suất và bảo vệ môi trường.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 450,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'image' => 'uploads/15.jpg',
                'title' => 'Văn hóa đọc đang trở lại mạnh mẽ',
                'slug' => Str::slug('Văn hóa đọc đang trở lại mạnh mẽ'),
                'content' => 'Trong kỷ nguyên số, văn hóa đọc sách vẫn duy trì và ngày càng được khuyến khích phát triển hơn.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 270,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'image' => 'uploads/16.jpg',
                'title' => 'Chuyển đổi số trong quản lý nhà nước',
                'slug' => Str::slug('Chuyển đổi số trong quản lý nhà nước'),
                'content' => 'Chuyển đổi số đang giúp cải tiến hiệu quả quản lý nhà nước và mang lại nhiều lợi ích cho xã hội.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 330,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'image' => 'uploads/17.jpg',
                'title' => 'Khám phá vũ trụ: Các thành tựu mới nhất',
                'slug' => Str::slug('Khám phá vũ trụ: Các thành tựu mới nhất'),
                'content' => 'Các sứ mệnh khám phá vũ trụ đang đạt được nhiều thành tựu quan trọng, mở ra những khám phá mới.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 380,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'image' => 'uploads/18.jpg',
                'title' => 'Công nghệ 5G và tác động đến đời sống',
                'slug' => Str::slug('Công nghệ 5G và tác động đến đời sống'),
                'content' => 'Công nghệ 5G đang thay đổi cách con người kết nối và tương tác trong mọi lĩnh vực của đời sống.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 490,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'image' => 'uploads/19.jpg',
                'title' => 'Chính sách bảo vệ môi trường mới nhất',
                'slug' => Str::slug('Chính sách bảo vệ môi trường mới nhất'),
                'content' => 'Nhiều chính sách bảo vệ môi trường mới đang được áp dụng nhằm giảm thiểu tác động của biến đổi khí hậu.',
                'is_breaking_news' => 1,
                'is_approved' => 1,
                'status' => 1,
                'views' => 410,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'image' => 'uploads/20.jpg',
                'title' => 'Khám phá đại dương: Những nghiên cứu tiên phong',
                'slug' => Str::slug('Khám phá đại dương: Những nghiên cứu tiên phong'),
                'content' => 'Các nhà khoa học đang thực hiện những nghiên cứu tiên phong để khám phá các bí ẩn của đại dương.',
                'is_breaking_news' => 0,
                'is_approved' => 1,
                'status' => 1,
                'views' => 370,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
